### ISSUE TITLE
The top level Makefile does unneccessary work

### ISSUE THREAD

**Issue by dreemkiller** [veracruz-project/veracruz#119]
**Describe the bug**
The top level Makefile rebuilds components unnecessarily, dramatically increasing incremental build time.

**To Reproduce**
As an example, run:
```
make sgx-veracruz-server-test
```
and then run it again:
```
make sgx-veracruz-server-test
```
Since nothing has changed between the builds, there should be nothing done for the second build. Instead, it rebuilds many of the components.

**Expected behaviour**
The second build should do practically nothing, as there is no new work to do.

**Environment, Git commit hash, and configuration**
This is being executed in a bash shell inside the veracruz-docker-container image built for SGX.

**Comment by dominic-mulligan-arm** [comment]
With the move to workspaces this is now irrelevant.
