### ISSUE TITLE
Code refactoring and tidying

### ISSUE THREAD

**Issue by dominic-mulligan-arm** [veracruz-project/veracruz#14]
We welcome any refactoring or cleanup of the Veracruz code-base.

**Comment by ShaleXIONG** [comment]
Document here for a few things that can be improved:
- `test-template<T>` functions in `sinaloa-test` and `veracruz-test` become extremely lengthy and difficult to maintain and extend now. One solution is to cut the functions into several function calls.
- There is a `Success` constructor in `VeracruzError` type in `chihuahua/error/common.rs`. (Low priority)
- May consider moving `sinaloa-test` to `sinaloa/test.rs`. However, details need to be sorted out. (Low priority)

**Comment by ShaleXIONG** [comment]
Pull out the state machine in chihuahua as a separate type with unified APIs, for example `next([condition])` and `error([condition])`.
