### ISSUE TITLE
Need to update our github AWS CodeBuild CI Access token

### ISSUE THREAD

**Issue by dreemkiller** [veracruz-project/veracruz#148]
**Requested feature**
Github has updated the format of their API authentication tokens, and our AWS CodeBuild CI Access token is still in the old format

**Motivation**
The new format has some unspecified "additional security benefits", which means they may have found some problems or opportunities for improvement in the old format.

**Comment by ShaleXIONG** [comment]
@dominic-mulligan-arm Is there any token bound to veracruz-owner account?

**Comment by ShaleXIONG** [comment]
No longer use AWS for CI.
