### ISSUE TITLE
`make trustzone-veracruz-server-test` builds `veracruz-client` even though it's not needed

### ISSUE THREAD

**Issue by dreemkiller** [veracruz-project/veracruz#151]
**Describe the bug**
When building `trustzone-veracruz-server-test`, it builds `veracruz-client` even though `veracruz-client` is not a necessary prerequisite for that target (`veracruz-server-test` does NOT use the `veracruz-client` crate)

**To Reproduce**
Execute `make trustzone-veracryz-server-test` from the `veracruz` root directory. Looking at the build log, it builds `veracruz-client`

**Expected behaviour**
It should not build unneeded crates, of which `veracruz-client` is one

**Environment, Git commit hash, and configuration**
This is happening on main as of today.

**Additional context**
When building a target in a makefile, common practice is to minimize the amount of rebuilding that must happen. A specific makefile target should only rely on dependencies that it actually needs to build successfully.

**Comment by ShaleXIONG** [comment]
Trustzone is not supported any more in Veracruz.
