### ISSUE TITLE
Veracruz doesn't build natively on aarch64 or aarch32

### ISSUE THREAD

**Issue by ericvh** [veracruz-project/veracruz#152]
**Describe the bug**
Too much hardcoding of crosstools

**Comment by dominic-mulligan-arm** [comment]
I believe that this is now no longer an issue.  @mathias-arm is that correct?

**Comment by mathias-arm** [comment]
I've built with AArch64 (https://github.com/veracruz-project/veracruz-docker-image/pull/24). AArch32 will likely not work. Is it somethi

**Comment by dominic-mulligan-arm** [comment]
Per the comment above, we support `Aarch64` and have no plans to support `Aarch32`, so I am closing this as complete.
