### ISSUE TITLE
Add AWS Nitro Enclaves test execution to the CI system

### ISSUE THREAD

**Issue by dreemkiller** [veracruz-project/veracruz#168]
**Requested feature**
Currently, the CI builds for SGX, builds for TrustZone, and runs the tests for TrustZone. We need to add build and run for AWS Nitro Enclaves.

**Motivation**
Unless the AWS nitro platform is being built and run in the CI system, the AWS Nitro support will atrophy and suffer from bitrot.

**Additional context**
We need to modify the CI system to start on an AWS-Nitro-supported system. To be clear, I'm not sure how to do this with the current CI system.

**Comment by dreemkiller** [comment]
It appears that adding AWS Nitro builds to veracruz can be done fairly easily: edit `buildspec.yml` to add
```
make nitro-veracruz-server-test-dry-run
make nitro-veracruz-test-dry-run
```
to the `build` commands.

It is likely that the docker image being used for the CI would need to be updated, though.

Actually running the Nitro tests is a different matter. This would require modifying the CodeBuild environment to be run on an EC2 instance that supports AWS Nitro Enclaves, which I'm not sure is possible.

**Comment by gbryant-arm** [comment]
Done in https://github.com/veracruz-project/veracruz/pull/258 and superseded by https://github.com/veracruz-project/veracruz/issues/514
