### ISSUE TITLE
Update toolchain and dependencies

### ISSUE THREAD

**Issue by mathias-arm** [veracruz-project/veracruz#170]
**Describe the bug**

The version of Intel SGX SDK used Veracruz is fairly out-of-date because of the version of Rust SGX SDK we are currently using. In practice that would mean moving:
- from: Rust SGX SDK v1.1.2, Intel SGX SDK v2.9.1, and Rust nightly-2020-04-07.
- to: Rust SGX SDK v1.1.3, Intel SGX SDK v2.12, and Rust nightly-2020-10-25.

**Additional context**

The toolchain is also blocking other updates (e.g. `wasmtime`).

**Comment by ShaleXIONG** [comment]
SGX is no longer supported in Veracruz.
