### ISSUE TITLE
VeracruzClient::get_results takes a path to the binary to retrieve results

### ISSUE THREAD

**Issue by geky** [veracruz-project/veracruz#175]
**Requested feature**
Consider splitting VeracruzClient::get_results (and the related protocol) into separate "VeracruzClient::perform_computation" and "VeracruzClient::get_results".

**Motivation**
With the recent WASI API changes, Veracruz computations are no longer multi-input -> single output, instead computations can result in many outputs represented as side-effects to the filesystem. The current VeracruzClient API does not reflect this, and there is no way to retrieve multiple output files without packing the outputs into a single file.

Being able to retrieve multiple files would be a nice feature, since computations can result in different types of output that may be reflected as different file types. This also would help separate binaries from outputs, which may help if we want to explore multi-binary computations in the future.

One concern may be security implications of have multiple readable files, but this should be handled by the permission set in our policy file.

**Additional context**
First noted here: https://github.com/veracruz-project/veracruz/pull/75/files#r657845798

**Comment by ShaleXIONG** [comment]
Close. The protocol buffer is split toto `compute` and `read_file`.
