### ISSUE TITLE
Push Veracruz Docker image to Docker hub 

### ISSUE THREAD

**Issue by basmaelgaabouri** [veracruz-project/veracruz#19]
Push the Docker Veracruz image to Docker Hub to make it easier to test and run Veracruz examples.

**Comment by dominic-mulligan-arm** [comment]
@ShaleXIONG, @dreemkiller, @hugovincent, @geky: what do you think of this idea?  We didn't do this before open-sourcing as it was not on the critical path to getting the code out in the open.  Is there any reason not to do this, now?

**Comment by hugovincent** [comment]
Making it easier for more people to try out Veracruz has got to be a good thing, I don't see any reason not to do this.

**Comment by dominic-mulligan-arm** [comment]
@basmaelgaabouri would you be happy to try and do this?

**Comment by basmaelgaabouri** [comment]
yes I would.

**Comment by dreemkiller** [comment]
Is this done?

**Comment by dreemkiller** [comment]
I think this is obsolete as we now use github to host our docker images
