### ISSUE TITLE
Improve Veracruz Dockerfile

### ISSUE THREAD

**Issue by basmaelgaabouri** [veracruz-project/veracruz#21]
Improve the Dockerfile to make it build faster and make the produced image lighter.

**Comment by dominic-mulligan-arm** [comment]
@basmaelgaabouri I think you had specific suggestions for how the Dockerfile could be improved, right?  Can you spell them out?

@ShaleXIONG I think we have also discussed the size of the resulting Docker image that is being produced in the past.  Would @basmaelgaabouri's suggested changes be beneficial in your opinion?

**Comment by basmaelgaabouri** [comment]
I would start by using a multistage build, it will for sure help reduce the build time, and more cleanup to reduce the size

**Comment by ShaleXIONG** [comment]
I am not an expert of Dockerfile, I think @basmaelgaabouri has more experience than me. It will be nice @basmaelgaabouri reduces the size of the final image.

**Comment by dominic-mulligan-arm** [comment]
Reducing the Docker size will also help with the CI.  @basmaelgaabouri, can you help improve the Docker situation?  Both reducing the image size and moving the image so that it is hosted on Docker hub are good ideas.

**Comment by dominic-mulligan-arm** [comment]
Resolved by recent changes in the Veracruz Docker image repository.
