### ISSUE TITLE
Improve readme and repository presentation

### ISSUE THREAD

**Issue by basmaelgaabouri** [veracruz-project/veracruz#23]
Make repository readme lighter and move detailed documentation to a special docs/ folder.

**Comment by dominic-mulligan-arm** [comment]
Actually, thinking more, maybe the contents of the current README can be moved into the Wiki so that it can be edited freely without opening up a pull request each time.  I thought @hugovincent saw some changes he wanted to make in it at one point.

**Comment by dominic-mulligan-arm** [comment]
This has now been done: the old README has been replaced with something lighter, with the contents now moved into our project-level wiki.
