### ISSUE TITLE
Add an optional "hash" field to each of the data input files in the policy

### ISSUE THREAD

**Issue by dreemkiller** [veracruz-project/veracruz#247]
**Requested feature**
Add an optional "hash" field to each of the data input files in the policy.
Add code in the runtime to enforce that data received from clients matches this hash value.

**Motivation**
Currently, we check the hash of the program being loaded, but additional data can also be considered part of the program state (consider ML model data).

Adding an optional hash to each of the data inputs, and enforcement of that hash, makes it so data can also be used as part of the enclave state.

**Additional context**
This was requested by @alexandref75

**Comment by ShaleXIONG** [comment]
Done. A policy has a section `file_hashes` containing expected hashes for files.
