### ISSUE TITLE
Should we rename the crates so the names make sense now?

### ISSUE THREAD

**Issue by dreemkiller** [veracruz-project/veracruz#26]
**Requested feature**
Should we rename the Rust crates so the names are more descriptive of what the crate does?
**Motivation**
When the project started, we named the crates after Mexican states. This was mostly because naming is hard, things were in flux, and we wanted to avoid long discussions about what to name things.

Now that things are more stable, it would probably be more inviting to users and developers to provide names for the crates the are more descriptive.

**Additional context**
Ideas (these are just ideas and of course there's room for discussion):

Jalisco -> SGXRootEnclave
Sonora -> TrustZoneRootEnclave
Tabasco -> ProxyAttestationServer
Colima -> TransportProtocol
Durango -> VeracruzClient
Sinaloa -> VeracruzServer

I'm not sure about Baja, Mexico City, and Chihuahua. We may not want to rename everything at this point.

With a mind for future ideas I have about isolating the platform-specific changes from each other, we may want to have separate crates for the SGX-specific server, TrustZone-specific server, etc.

Ideas for these names: SGXServer, TrustZoneServer.

**Comment by dominic-mulligan-arm** [comment]
I think so.   I think with the number of new components it's hard to keep track of what all the crates do now, even when you work on the project, with all of the non-descriptive names.  Suggestions for the remaining crates:

Chihuahua -> ExecutionEngine
Baja -> TrustedSessionManager
MexicoCity -> TrustedRuntimeManager

**Comment by ShaleXIONG** [comment]
Tlaxacala -> WASMChekcer.
Veracruz-test -> Example, so newcomers know where to start?
Several type names also follow the component name. It should be changed in a consistent way.

**Comment by dreemkiller** [comment]
Agreed on the WASMChecker name.

However, I don't think `veracruz-test` works well as an example. It uses a few abstractions (such as `test_template`) to reduce code duplication in the tests that make it harder to understand than an example should be.

**Comment by hugovincent** [comment]
I'm strongly in favour of descriptive names 👍 .

**Comment by dominic-mulligan-arm** [comment]
There seems to be a strong consensus that we should rename the various components to something more descriptive.  I'll close this question and create an issue for this task.  Consensus yesterday was this was something that @geky could do to familiarise himself with the Veracruz codebase.

**Comment by dominic-mulligan-arm** [comment]
See #33.
