### ISSUE TITLE
Add support for AWS Nitro Enclaves

### ISSUE THREAD

**Issue by dreemkiller** [veracruz-project/veracruz#27]
**Requested feature**
Add support for AWS Nitro Enclaves

**Motivation**
We currently support SGX and TrustZone. AWS recently launched their Nitro Enclaves. We should add support for them.

**Additional context**
AWS launched Nitro Enclaves last week. Details are online (https://aws.amazon.com/ec2/nitro/nitro-enclaves/)

**Comment by dreemkiller** [comment]
AWS currently only supports 1 enclave per EC2 instance.
Their CLI tool, and their documentation, has room for more than one enclave per instance, but this is not currently supported. I emailed support, and they confirmed this. They would not commit to a schedule for support for multiple enclaves per EC2 instance.

Veracruz requires multiple enclaves: the root enclave which performs native attestation with Tabasco, and the Mexico City enclave, which gets a PSA Attestation token from the root enclave and performs the actual computations.

I have worked things out to the following two "solutions" (one is a hack):
1. Start another EC2 instance, run the root enclave on that. This means testing will be a big pain (it can take minutes to launch an EC2 instance, and there's a lot of work that needs to go into this)
2. (This is the insecure hack) Start the root enclave, perform native attestation, then export the generated key into Sinaloa (which can run part of the nitro-root-enclave software as a library, in a separate thread). This will allow easy testing, but is NOT SECURE. This is not a large amount of work beyond what's already been done.

I think it is very important for Veracruz to have a viable, secure, cloud solution. As of right now, SGX is our only truly secure platform (based on our security assumptions, of course). We've had to hack TrustZone as a demonstration platform, I'm not too comfortable having to hack another one. A fully secure AWS Nitro Enclave solution would be great for Veracruz. However, there's some work to get there (This hitch maybe adds ?2? days to the effort), and it will greatly slow down our tests.

**Comment by dominic-mulligan-arm** [comment]
I think we should not introduce further hacks, like you said.

If, with Nitro support, we manage to get tests integrated properly into the CI then the minutes of overhead in starting up another EC2 instance is going to be dwarfed by the ~3 hour build time that we currently have for a full build and which will run before the tests.  Really, the overhead is only going to be problematic for local testing during development of new features.  For the majority of new features that are not directly related to Nitro, but are just general hacking on the runtime, we can probably tolerate a few extra minutes when performing a final check.  Do you agree, or am I misunderstanding how intrusive this will be?

**Comment by dreemkiller** [comment]
I agree with your analysis on the testing overhead. My thoughts were mostly about poor me during development, but you make a really good point about the CI timing.

The other problem about doing it "correctly" now: Some day in the unspecified future, we will be able to put both enclaves on the same instance. If that day is in 2 weeks (unlikely), we will have done a lot of work to then throw it away. 

If that day is in 2 years (also unlikely), the effort of writing the code makes more sense.

Given AWS's track record, I suspect the most likely scenario is somewhere on the order of 6 months, which... makes the time/code investment less clear.

I think I will move forward with option 1, as I am uncomfortable with a hack like that (especially since I view the most likely way someone will use Veracruz is with Nitro at this point).

**Comment by dominic-mulligan-arm** [comment]
@dreemkiller is this now completed?

**Comment by dreemkiller** [comment]
We still need to get it up and running in the CI, which may involve a few minor code changes, as well as changes to veracruz-docker-image
