### ISSUE TITLE
Slack Access

### ISSUE THREAD

**Issue by drasko** [veracruz-project/veracruz#292]
While README states that [Slack is open to the public](https://github.com/veracruz-project/veracruz#get-involved), looks like it is reserved for `@linuxfoundation.org` domain.

Can we have more clear instructions how to obtain access to this Slack workspace:
- Is it reserved only to the mebers of the constorium?
- If not, how to contact CCC workspace admin (what would be tthe proper email address)?

![veracruz-slack](https://user-images.githubusercontent.com/149944/144769807-8c4ad39f-0359-4c2c-93ae-26630315c0a9.png)

**Comment by dominic-mulligan-arm** [comment]
Hi @drasko, thanks for the report.  The Veracruz channel is indeed open to the public.  As far as I know, anybody can also sign in to the CCC Workspace, too (we've certainly got people from a number of organisations, already, in the Veracruz channel who are not involved in the CCC).  My reading of that screen is that you can either sign in with a `linuxfoundation.org` or `cosmian.org` address, if you're somehow affiliated with either of those two organisations, or use a Google or an Apple account to sign in, if not.

**Comment by dominic-mulligan-arm** [comment]
Actually, can you tell me which email you wish to use, and I can invite you in from within the CCC workspace?

**Comment by drasko** [comment]
Hi @dominic-mulligan-arm, thanks for the support. I did try clicking on Gmail, but it fails, as it demands `@linuxfoundation.org` address. Maybe someone from LF hanged accesss rules recently?

My mail is `drasko.draskovic@gmail.com`, but I would prefer that we fix the documentation explaining people how they can join, as apparently [here](https://confidentialcomputing.io/get-involved/) as well only this type of access is demanded and no appropriate admin e-mail is left, so that people can demand an access.

**Comment by dominic-mulligan-arm** [comment]
@drasko, yeah, definitely this needs fixing as I don't really want to be inviting everybody who wants to join the CCC workspace on a case-by-case basis!  (In your case, though, I've just sent out an invite to your email address from inside the workspace, which you should hopefully receive soon.  I will also follow up with the CCC too...)

**Comment by drasko** [comment]
Thanks @dominic-mulligan-arm. I'll close this one then.
