### ISSUE TITLE
Rename the Veracruz components to something more descriptive

### ISSUE THREAD

**Issue by dominic-mulligan-arm** [veracruz-project/veracruz#33]
As discussed in #26, the various Veracruz components are named after Mexican states.  Whilst this worked in the early stages of the project, when we had relatively few components to worry about, the project has now grown to the point where we have a large number of components, each with a Mexican name which is not tied to the purpose of that component.  When working on the project full-time, it is hard to keep track of the purpose of each component, and newcomers will undoubtedly have it worse.  The consensus, when this issue was discussed, was that these names should now change to something more descriptive, with the suggestions (still open to change or refinement):

- Jalisco -> SGXRootEnclave
- Sonora -> TrustZoneRootEnclave
- Tabasco -> ProxyAttestationServer
- Colima -> TransportProtocol
- Durango -> VeracruzClient
- Sinaloa -> VeracruzServer
- Chihuahua -> ExecutionEngine
- Baja -> SessionManager
- MexicoCity -> RuntimeManager
- Tlaxcala -> WASMChecker

Note that this change will touch almost everything in the Veracruz codebase:

- All crate names need updating, and any references to crates in the Veracruz source,
- All Makefiles and build scripts,
- All documentation (e.g. the `COMPONENTS.markdown` file, as well as the contents of the project wiki),
- All comments in the various source files.

**Comment by geky** [comment]
The ongoing renaming raises a question about what the CLI names should be. I was thinking of these, thoughts?

I added a common "vc" prefix which lets you "install" Veracruz to /usr/bin without name conflicts, and tried to use easy to type names.

- tabasco -> vc-pa-server
- sinaloa -> vc-server
- durango -> vc-client
- generate_project -> pgen -> vc-pgen
- freestanding-chihuahua ->freestanding-execution-engine -> vc-exec-freestanding (maybe could be vc-test or just vc-exec?)

**Comment by dominic-mulligan-arm** [comment]
With the completion of the great renaming, this is now resolved.
