### ISSUE TITLE
There's recently been a regression on Nitro

### ISSUE THREAD

**Issue by dreemkiller** [veracruz-project/veracruz#349]
**Describe the bug**
When veracruz-server-test is running on a nitro-enabled, platform, we see the following error:
`VeracruzServerNitro::new complete. Returning
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unspecified', /usr/local/cargo/git/checkouts/rustls-59aebdcc975fb2c1/39f3996/src/rand.rs:14:10`

**To Reproduce**
Start with a fresh environment, and execute:
`make nitro-veracruz-server-test`
Most of the tests will fail.

When you run one test by itself, for example `test_phase3_linear_regression_one_data_with_attestation`, you will see the above error message

**Expected behaviour**
Tests should pass

**Environment, Git commit hash, and configuration**
Working from the docker file from the repo. Executing inside the container as root.

**Comment by mathias-arm** [comment]
This might not fix the issue bug you should be using:
```
make -C `workspaces/nitro-host` test-server
```

**Comment by dreemkiller** [comment]
Have the READMEs been updated to reflect that? I haven't seen that on main.

**Comment by egrimley-arm** [comment]
The `nitro-veracruz-server-test` target was removed on 4 Mar 2022 and `NITRO_INSTRUCTIONS.markdown` has been recently updated (#481) and tested. So I'm closing this issue.

(I'll just mention in passing that the instructions specify using `PROFILE=release`. I think it doesn't work without that, so perhaps that should be investigated or the default should be changed.)
