### ISSUE TITLE
Clearly document all IP addresses and ports used by various Veracruz components

### ISSUE THREAD

**Issue by dominic-mulligan-arm** [veracruz-project/veracruz#365]
**Requested feature**

Several Veracruz components communicate with each other over TCP connections (depending on the isolation technology in question).  The ports (and addresses) used for these connections should be clearly documented, and ideally made configurable, somehow.

**Motivation**

For Linux, the Veracruz Server and Runtime Manager communicate over a TCP socket on `localhost:6000`.  This fact is currently not documented clearly anywhere, and if port `6000` is already in use for some reason, we run the risk of Veracruz failing with a hard-to-understand error message.

**Comment by elroykanye** [comment]
Hello @dominic-mulligan-arm.
I am Elroy, an outreachy internship applicant and I will like to work on this issue.

**Comment by dreemkiller** [comment]
Hello @ekroykanye. This is a perfect first issue to work on! Feel free to start work on it, and hit us up on the public slack channel(which I see you are a member of) if you have questions or need some help!

**Comment by elroykanye** [comment]
Okay, will do
