### ISSUE TITLE
Add build target for `cargo clippy` in Veracruz Makefile

### ISSUE THREAD

**Issue by dominic-mulligan-arm** [veracruz-project/veracruz#37]
At the moment we do not have support for the [Clippy linter](https://github.com/rust-lang/rust-clippy) in the Veracruz Makefile.  Some of Clippy's lint groups would be useful to check on the Veracruz codebase, especially those related to correctness, performance, and idiomatic Rust code style.  In the past, I quickly experimented with Clippy on Veracruz but found that lint warnings in our code were swamped by warnings originating from our dependencies.  Apparently, this cannot be turned off (see e.g. [here](https://stackoverflow.com/questions/40518446/exclude-dependencies-when-running-clippy)).  However, maybe this situation has changed, or maybe there's some way of filtering the lint warnings to produce warnings originating from only our code, or similar, which should be investigated.

**Comment by Mo-Fatah** [comment]
As of my understanding, should [this](https://github.com/rust-lang/rust-clippy/pull/6188) solve it now ?

**Comment by Mo-Fatah** [comment]
After being able to exclude dependencies from `clippy` warnings, I have a proposal for `clippy` in Veracruz

1. Add `clippy` target to each `Makefile` in all workspaces. Each `clippy` target will scan only the `members` of the specified workspace. For example, running `make clippy` inside `veracruz/workspaces/linux-host` will generate only warnings for the [members](https://github.com/veracruz-project/veracruz/blob/b350e696ae75defe20766b2c2acc07c4b3a7cd54/workspaces/linux-host/Cargo.toml#L16) of the `linux-host` workspace excluding all dependencies. 

2. Add `clippy` target to `workspaces/Makefile`, which will invoke all `clippy` targets in all workspaces.

3. After making sure that our `clippy` targets are behaving as expected, I think Veracruz team should agree upon our `clippy` configurations.
  
4. Add `clippy` to our CI workflow. We can either 
   - add it as an independent `job` that will invoke `clippy` targets in all workspaces 
   - or add it as an included `step` in each `job` , and each job will invoke its `clippy` target from the corresponding `Makefile`

**Comment by dreemkiller** [comment]
We have this
