### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by ShaleXIONG** [veracruz-project/veracruz#377]
**Requested feature**
We want more examples, particularly, in the following areas, (but not restricted):
- I/O related examples. This can give us more insight into whether our implementation of WASI makes sense and works as expected. 
- Pipeline examples. This will be similar to the Linux pipeline  `command1 | command2 | command3`. In the Veracruz content, the first program, `prog_1`, writes the result to a file, e.g., `result_1.dat` and the second program `prog_2` reads the previous result in `result_1.dat` and then writes the new result to, e.g., `result_2.dat` and so on. In this setting, the WASM programs may be compiled from different source languages such as a combination of Rust and C.
- Examples in other languages. More languages can be compiled to the WASM binaries now. It is worth exploring and providing a guide to compile more languages to WASM/WASI binaries.

Note that, each bullet point above is a large group of examples, and there are other examples we might fail to cover. Everyone is welcome to contribute here. 

**Motivation**

More examples can help us to identify new use-cases and features for Veracruz.

**Additional context**

This is a suitable starting point for people wanting to work on Veracruz. Newcomers will learn how to build and use our docker image under the directory `docker`, and then compile the entire Veracruz project to a backend, (the easiest one is Linux), then use the `sdk/freestanding-execution-engine` to check if the new examples can be executed in Veracruz runtime.

**Comment by paul-111** [comment]
Can i work upon the 3rd example? Providing a guide to compile more languages to WASM/WASI binaries?

**Comment by ShaleXIONG** [comment]
> Can i work upon the 3rd example? Providing a guide to compile more languages to WASM/WASI binaries?

Hi, of course. This issue is open for everyone to contribute.

**Comment by ShaleXIONG** [comment]
> Hi @ShaleXIONG , I am a little confused with the second point (Pipeline examples). How would I feed more than one program to the `freestanding-execution-engine` , while it accepts only one file after the `--program` parameter.
> 
> `USAGE: freestanding-execution-engine --arg <ARG>... --dump-stderr --dump-stdout --enable-clock --input-source <DIRECTORIES>... --output-source <DIRECTORIES>... --program <FILE> `

That is a good question. I do not think `freestanding-execution-engine` can call more than one program. I will patch it soon (in days). However, if you use the full Veracruz, with proper client and server sides, it has no such limitation. Free feel to try before the patch on `freestanding-execution-engine` is live.
