### ISSUE TITLE
Add WABT to our development docker images

### ISSUE THREAD

**Issue by geky** [veracruz-project/veracruz#382]
**Requested feature**
Add WABT to our development docker images

**Motivation**
[WABT](https://github.com/WebAssembly/wabt) is an incredibly valuable tool for developing and exploring WebAssembly. It would be nice if we could use it inside our docker images. 

**Additional context**
A specific use case is that these tools would be nice to add to CLI_INSTRUCTIONS.md and examples.

**Comment by dreemkiller** [comment]
The `wasm-checker` uses `WABT` already. So, we have `WABT` as part of our build (whether or not this is a good idea is open for debate).

**Comment by geky** [comment]
Though that's not really something we can write instructions against, in case `wasm-checker` is removed or renamed

**Comment by dreemkiller** [comment]
True, that.

However, it would be a shame to have both in there. If we add it to the docker container, we should remove it from the build process and just use the installed version of the library.

**Comment by geky** [comment]
That can be done, probably

**Comment by geky** [comment]
Poking around `wasm-checker` a bit more, I'm not sure removing the deduplicating `wabt` is a great idea.

In `wasm-checker` we're actually linking directly against the `wabt` sources:
https://github.com/veracruz-project/veracruz/blob/0283b383fbe7c553b97a8b07b2fc435e2c63822d/sdk/wasm-checker/Makefile#L14

I don't know the history of `wasm-checker`, but I'm not actually sure this is supported or a public API. I haven't found any documentation over it, and it seems like the `libwabt.a` file is just generated as an intermediary for building all of the binaries. Fortunately we're specifying a specific version in `wasm-checker`, so I don't think we have to worry about API breakage:
https://github.com/veracruz-project/veracruz/blob/0283b383fbe7c553b97a8b07b2fc435e2c63822d/sdk/wasm-checker/Makefile#L17

But this means we'd probably want to keep `wasm-checker`'s wabt sources close.

In https://github.com/veracruz-project/veracruz-docker-image/pull/38 I currently have it cleaning up the source files during installation, I believe this means the source won't be in the final docker size.

**Comment by mathias-arm** [comment]
This issue made sense to me if we could build `wabt` ahead of time (there are some space saving opportunities with multi-stage builds). Now that it's an additional copy of `wabt`, it seems much less interesting in particular because the added build time is significant.

**Comment by geky** [comment]
The main benefit of installing wabt outside of wasm-checker is that it's available in the path and available without needing to build the full sdk.

I suppose the build time makes this untenable then?

Another option would be to move wabt up a level in the sdk and install the binaries similarly to how we install vc-fee, vc-pgen, etc.

**Comment by geky** [comment]
I just realized wabt is available in the 20.04 packages. maybe this should wait/come with an docker version upgrade? Though this might be a bit more difficult for me to test cohesively...
https://packages.ubuntu.com/focal/wabt

**Comment by geky** [comment]
per @mathias-arm we are upgrading to 20.04 as a part of https://github.com/veracruz-project/veracruz/pull/367, so this should probably just wait for that then. With 20.04 wabt just becomes another apt-get package.
