### ISSUE TITLE
Test cases on calling multiple programs in Veracruz

### ISSUE THREAD

**Issue by ShaleXIONG** [veracruz-project/veracruz#396]
**Requested feature**
Add test cases on calling multiple programs in sequence in Veracruz.
- Add at least one case in `veracruz-test`.
- Add parameters in `freestanding-execution-engine`.

**Motivation**
This links to #377. This issue provides minimum examples so further examples can be added.

**Additional context**
Requested and reported by @Mo-Fatah

**Comment by Mo-Fatah** [comment]
@ShaleXIONG  what is the policy of the environment variables? 
For examples, If I run multiple programs in FEE and I provided the parameter `--arg 100` , Will this `100` considered an environment variable for the first program ONLY or all the programs ?

**Comment by ShaleXIONG** [comment]
> @ShaleXIONG what is the policy of the environment variables? For examples, If I run multiple programs in FEE and I provided the parameter `--arg 100` , Will this `100` considered an environment variable for the first program ONLY or all the programs ?

It will be passed to all programs actual. In fact we did not have much test on passing environment variables in Veracruz itself.
