### ISSUE TITLE
Move from TLS1.2 to TLS1.3

### ISSUE THREAD

**Issue by dominic-mulligan-arm** [veracruz-project/veracruz#4]
At the moment we are using the RusTLS Rust TLS library with TLS1.2 for protected communications between the trusted Veracruz runtime and various principals involved in the computation.  We should consider adopting TLS1.3 instead.

**Comment by egrimley-arm** [comment]
We have moved from using `rustls` to `rust-mbedtls`. The places where TLS 1.2 is specified can currently be found with `grep ssl::config::Version */src/*.rs`.

The Rust wrapper, `rust-mbedtls`, does not currently have `Tls1_3`, but development versions of the underlying C library, Mbed TLS, have at least partial support for TLS 1.3, and TLS 1.3 does not come with major API changes in Mbed TLS, so there is a good chance that it would be quite easy to switch.

I hope to try it quite soon.

**Comment by egrimley-arm** [comment]
This was done by #494.
