### ISSUE TITLE
Make IceCap server tests more reliable

### ISSUE THREAD

**Issue by egrimley-arm** [veracruz-project/veracruz#429]
Problems we have seen include:

* A single test taking more than 30 minutes on GitHub with `PROFILE=dev` and passing (apparently).
* The entire `server-test` suite finishing in about 3 minutes on `localci` without `PROFILE=dev` and passing (apparently).
* Huge variation in how long a test run takes both on GitHub and on `localci`.

The command to run just the IceCap server tests is:

`make -C workspaces/icecap-host test-server`

**Comment by dominic-mulligan-arm** [comment]
I also saw this yesterday: on `localci` the `icecap` `server-test` seemed to hang indefinitely with `PROFILE=dev` on the `main` branch.  There were a few diagnostic about allocating pages produced on the command line, but then it just seemed to loop forever, though I don't think I waited long enough to see whether 30 minutes would suffice for it to do anything...

**Comment by egrimley-arm** [comment]
Though this test has sometimes succeeded in about 5 minutes,
`test_phase1_new_session` timed out after 2400 s here:
https://github.com/veracruz-project/veracruz/runs/6211854461

**Comment by egrimley-arm** [comment]
Here we seem to have the same problem after #440 was applied:
https://github.com/veracruz-project/veracruz/runs/6311243609

**Comment by mathias-arm** [comment]
> Here we seem to have the same problem after #440 was applied: https://github.com/veracruz-project/veracruz/runs/6311243609

It's a different issue. The changes in the draft PR make IceCap crash.
