### ISSUE TITLE
Veracruz fails if result size is too large

### ISSUE THREAD

**Issue by federicobozzini** [veracruz-project/veracruz#477]
**Describe the bug**
When the result of a computation is too large (>= 18378 bytes on my machine) Veracruz fails with the following error:
`VeracruzClient: TransportProtocolError: PartialBuffer(5).`

This is not related to what happens to the result (redirection to a file or to stdout).

**To Reproduce**
The simplest program I could create to reproduce the error is the following:

```rust
use std::{
    fs::{write},
    path::{PathBuf},
};

fn main() -> anyhow::Result<()> {
    let a: [u8; 18378] = [65; 18378];
    write(PathBuf::from("/output/enc.dat"), &a)?;
    Ok(())
}
```
If the size of `a` is 18377 the program runs correctly. If the size is 18378 the program fails.

To reproduce just run this example.

**Expected behaviour**
The expected behaviour would be to not have a limit on the result of the output or to have this limitation documented somewhere.

**Screenshots, terminal output, or logs**
Final logs of the computation in case of failure:

```
Connecting to 127.0.0.1:3017
Requesting compute of <enclave>//program/example-binary.wasm
Reading <enclave>//output/enc.dat into <stdout>
VeracruzClient: TransportProtocolError: PartialBuffer(5).
```

**Environment, Git commit hash, and configuration**
I'm using Veracruz on Docker (localci environment), commit `4f1fe403e1e1fc10ab774b1fb14f1477f859f366`. No special configuration.

**Additional context**
Please add any other context about the problem here.

**Comment by dreemkiller** [comment]
which platform are you seeing this on? Linux? Nitro? Icecap?

**Comment by gbryant-arm** [comment]
Thanks for spotting the bug @federicobozzini . There must be an issue in the buffering mechanism. I'm investigating

**Comment by egrimley-arm** [comment]
Here are the copy-paste instructions for reproducing the problem:
```
# adapted from .github/workflows/main.yml
sed -n '/``` bash/,/```/{/```/d; p}' CLI_QUICKSTART.markdown \
  | sed ':a; /\\$/{N; s/\\\n//; ta}' \
  | sed -n '/^\$/{s/^\$ \?//; p}' \
  > CLI_QUICKSTART.markdown.sh

# experiment with different values here:
size=999999
cat > sdk/rust-examples/shamir-secret-sharing/src/main.rs <<EOF
use std::{
    fs::{write},
    path::{PathBuf},
};

fn main() -> anyhow::Result<()> {
    let a: [u8; $size] = [65; $size];
    write(PathBuf::from("/output/shamir.dat"), &a)?;
    Ok(())
}
EOF

bash -euxo pipefail CLI_QUICKSTART.markdown.sh
```

(Unfortunately that snippet does not kill the server processes when the test fails. I cleaned up manually with `ps auxw` and `kill`.)

I have checked that:

* On 4f1fe403e1e1fc10ab774b1fb14f1477f859f366 it fails as described above at `size=18378`.
* On f3c8cc16f96e17cc34215b0beefe865bc709241f it fails as described above at `size=65519`.
* On e01d82534c3f4232ba35fa72d6cbb6870cf33194 (today) it succeeds at `size=999999`.

(It fails at `size=9999999` with `InstructionTrap(MemoryOutOfBounds)` but that sounds like an entirely different problem!)

So it looks as though #476 has indeed fixed it so I'm closing this issue.
