### ISSUE TITLE
Remove `sleep` in `veracruz-server` on Linux enclave start up

### ISSUE THREAD

**Issue by dreemkiller** [veracruz-project/veracruz#478]
**Requested feature**
Currently, when `veracruz-server` starts a Linux "enclave", it performs a 2 second `sleep` while it waits for the process to start. This is kludgy and prone to spurious errors.

We should remove that `sleep` and replace it with a more deterministic solution.

**Motivation**
Current solution is a kludge and is prone to spurious errors

**Additional context**
One proposal is to replace the `sleep` with a listener on a socket. When the enclave process starts, it should connect to that socket port, indicating to the server that it has completed start up and is ready to accept commands.

This listener should have a timeout on it, so that in the event the enclave process fails to start, we get a definitive error instead of hanging.

**Comment by egrimley-arm** [comment]
#468 is a possible solution for this, though it does not currently have the time-out.

**Comment by egrimley-arm** [comment]
I've added a 30-second time-out in #468 using `nix::unistd::alarm::set`.

**Comment by egrimley-arm** [comment]
Closing this because of #478.
