### ISSUE TITLE
Remove `sleep` on Nitro enclave startup

### ISSUE THREAD

**Issue by dreemkiller** [veracruz-project/veracruz#479]
**Requested feature**
Currently, when `veracruz-server` starts a Nitro enclave, it performs a 2 second `sleep` while it waits for the enclave to boot. This is kludgy and prone to spurious errors.

We should remove that `sleep` and replace it with a more deterministic solution.

**Motivation**
Current solution is a kludge and is prone to spurious errors

**Additional context**
One proposal is to replace the `sleep` with a listener on a socket. When the enclave completes its boot, it should connect to that socket port, indicating to the server that it has completed start up and is ready to accept commands.

This listener should have a timeout on it, so that in the event the enclave process fails to start, we get a definitive error instead of hanging.

**Comment by egrimley-arm** [comment]
Closing this because of #485.
