### ISSUE TITLE
"make localci-run" seems to rebuild the container image each time

### ISSUE THREAD

**Issue by egrimley-arm** [veracruz-project/veracruz#499]
If the running container (`docker ps`) has been killed, but the image (`docker images`) is still there, it would be nice if `make localci-run` could just run the existing image rather than waste time recreating it.

Likewise for the other container images in `docker/Makefile`.

**Comment by dreemkiller** [comment]
This is a difficult problem. I have yet to find a good way to use docker containers as prerequisites for `Makefile` targets.

In the past, I've created dummy files after building images, and using those as the prerequisites (also using those as the target of the docker build). I suspect this would result in some bizarre corner cases though.

**Comment by mathias-arm** [comment]
I removed the dependencies altogether in #645 (specifically [8816e63](https://github.com/veracruz-project/veracruz/pull/645/commits/8816e63a12edf1e6f585f296abeccf1f8af65ecc)). The instructions state that you have to run `make localci-build` then `make localci-run`. Saving this one step is not worth the downsides of having to do superfluous rebuilds of the image.
