### ISSUE TITLE
Add support for PSA Crypto to the Veracruz host ABI

### ISSUE THREAD

**Issue by dominic-mulligan-arm** [veracruz-project/veracruz#5]
There are several interesting use-cases for Veracruz that require the use of cryptographic functionality by the executing WASM program inside the enclave (for example: deniable encryption).  At the moment, the Veracruz host ABI does not present any cryptography-related functionality, which forces programmers wishing to use cryptographic to link a cryptography library into WASM program directly.  This is both error prone and bloats the size of the WASM binary.  Instead, the Veracruz host ABI could be extended to provide common cryptographic functionality, built around Arm's PSA Crypto API, and make this available to the WASM program.  We would need:

1. Some candidate use-cases to drive development,
2. A candidate ABI design,
3. Implementation of the required cryptographic primitives in the trusted Veracruz runtime,
4. Extension of `libveracruz` to expose the PSA Crypto API to the WASM program.

**Comment by ShaleXIONG** [comment]
This is solved by the use of the native module of PSA.
