### ISSUE TITLE
Entropy problem on Nitro

### ISSUE THREAD

**Issue by gbryant-arm** [veracruz-project/veracruz#507]
**Describe the bug**
On some Nitro machines, requesting entropy by whether reading `/dev/random` or sending a `getrandom` syscall results in failure: the function call hangs and does not return immediately (or ever). This might be due to entropy shortage or incorrect entropy initialisation.
Passing `GRND_RANDOM` or `GRND_NONBLOCK` to `getrandom()` doesn't seem to make any difference.
Reading from `/dev/urandom` works.

**To Reproduce**
Call libc's (musl's) `getrandom()` or read `/dev/random` inside Nitro and wait for the return... forever (doesn't happen on every Nitro machine)

**Expected behaviour**
`getrandom()` or `/dev/random` should promptly return random bytes.

**Potential solutions**

##### 1. Use the NSM library
On Nitro, it is recommended to use AWS' NSM library for RNG.
The functions of interest are `nsm_get_random()` and `aws_nitro_enclaves_library_seed_entropy()`, the latter calling `nsm_get_random()` and seeding `/dev/random` with the returned random bytes.
It's curious that `/dev/random` is not seeded automatically by the kernel whenever the `getrandom` syscall is received.
Several approaches can be considered to redirect external dependencies to the right RNG:
* Use Veracruz's `platform-services`: In Veracruz, `platform-services` exposes `getrandom()` that calls functions from the NSM lib. WASM programs calling `getrandom()` are automatically redirected to it, but linking external dependencies, especially C code, against it is trickier (cf. #511)
* Mbed TLS specific: Pass a pointer to a custom RNG when initialising mbedtls (`mbedtls_ssl_conf_rng()`)

##### 2. Read RN from `/dev/urandom` (quick workaround)

**Comment by dreemkiller** [comment]
What are the properties of the instances that are experiencing the failures?
Have they been up a long time? Because originally, `nsm` was not plumbed into `/dev/random`. Is it possible that the failures are happening on instances launched before that change was made?

**Comment by dreemkiller** [comment]
Here are some thoughts about `/dev/random` vs `/dev/urandom`: https://www.2uo.de/myths-about-urandom/

TL/DR: `/dev/urandom` should be fine.

**Comment by gbryant-arm** [comment]
> What are the properties of the instances that are experiencing the failures? Have they been up a long time? Because originally, `nsm` was not plumbed into `/dev/random`. Is it possible that the failures are happening on instances launched before that change was made?

I've only found one Nitro machine experiencing the failure so far. It was created at the same time as the ones that are fine, and has been rebooted many times since then. I don't know what is wrong with that machine.

**Comment by gbryant-arm** [comment]
Opened an issue upstream: https://github.com/aws/aws-nitro-enclaves-sdk-bootstrap/issues/15
