### ISSUE TITLE
Pull out the state machine from the execution engine.

### ISSUE THREAD

**Issue by ShaleXIONG** [veracruz-project/veracruz#54]
The state machine for controlling the Veracruz becomes more complex given the streaming extension. The implementation of the machine is currently mixed with the execution engine (Chihuahua). This becomes a barrier for maintenance. Separately, the state machine relies on the execution engine to __set__ the correct state via explicit setters. Here a better solution here is to pull out the state machine as a more self-contained file or component with a unified API, `next([Condition])` for example.

**Comment by dominic-mulligan-arm** [comment]
This is now irrelevant with the removal of the state machine in the provisioning process.
