### ISSUE TITLE
Need to restore random generation of the enclave name

### ISSUE THREAD

**Issue by dreemkiller** [veracruz-project/veracruz#55]
**Describe the bug**
Long, long ago, the enclave name used as the name for the TLS server was randomly generated.
While implementing support for TrustZone, it was hardcoded to "ac40a0c" to simplify things (and the random number generator wasn't working).
It needs to be changed back to being randomly generated.
This is not a security issue (it would be perfectly valid for it to remain static), but it's bad optics.

Also, we should remove the "get_enclave_name" functionality and instead embed the name in the attestation tokens (this has never been done, so.. new feature, yay!)

**To Reproduce**
Every time the enclave starts, it just hard codes it to the above value.

**Expected behaviour**
Each boot of the enclave should generate a new, different name.
Now, on the simulated TrustZone platform, it is likely to always produce the same value, because the RNG is seeded with the same value each time. But for SGX (and Nitro, in the near future), the value should be different every time.

**Screenshots, terminal output, or logs**
N/a

**Environment, Git commit hash, and configuration**
n/a

**Additional context**
n/a

**Comment by ShaleXIONG** [comment]
I believe this issue might be irrelevant now?
