### ISSUE TITLE
Linux Runtime Manager panics printing to stdout

### ISSUE THREAD

**Issue by gbryant-arm** [veracruz-project/veracruz#565]
**Describe the bug**
On Linux, the Runtime Manager panics printing to stdout:
```
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1164:9
```
~~Incidentally, this results in Veracruz-Server's CPU usage spiking to 100%~~ (fixed in #567) 
This happens because VC-Server is using `stdout` to sync with RM, then destroys the pipe after sync, resulting in subsequent writes to `stdout` to fail.

**To Reproduce**
Add a `println!` to any dependency of the RM, e.g. in `execution-engine/src/fs.rs`.
Recompile and run Veracruz end-to-end.

**Expected behaviour**
The Runtime Manager shouldn't fail, let alone panic.

**Possible solutions**
1. As a workaround, `eprintln!` should be used for debugging instead of `println!`, however we don't have much control over what native modules do. For example, TensorFlow Lite, used by the TensorFlow inference native module, prints all sorts of stuff to `stdout`
2. Use a named pipe for the sync channel to avoid interfering with standard streams
3. Redirect `stdout` "back to itself" (or `/dev/null` in release mode?) after the pipe is destroyed on the VC-Server side. Is this possible on IceCap?

**Comment by egrimley-arm** [comment]
Why does code in the Runtime Manager need to print to `stdout`? What should happen with data written to `stdout`, on Linux or other targets?

**Comment by gbryant-arm** [comment]
That's mainly for debugging purposes. Admittedly we should use `eprintln!` or `info!` for that

**Comment by gbryant-arm** [comment]
Hmm actually some native modules might use `stdout`. `tflite-rs` does that, and that's an issue

**Comment by egrimley-arm** [comment]
Would it be a solution to get the Runtime Manager to redirect `stdout` to a file before it starts running the application?

**Comment by gbryant-arm** [comment]
Native modules could write to any file, `stdout` is only one of them.
That could be a short-term solution though, until we figure out how to sandbox native modules. The other short-term solution is to fix this bug.

**Comment by egrimley-arm** [comment]
I've reproduced "Veracruz-Server's CPU usage spiking to 100%" and I'm going to look at that first. It's probably going into a loop repeatedly reading EOF and failing to recognise it and give up.

**Comment by gbryant-arm** [comment]
> I've reproduced "Veracruz-Server's CPU usage spiking to 100%" and I'm going to look at that first. It's probably going into a loop repeatedly reading EOF and failing to recognise it and give up.

Nice! This is not the first time I'm seeing this. Seems like the common denominator is the server waiting for a message from the RM or the client.

**Comment by dreemkiller** [comment]
For most platforms, allowing native modules (or the wasm) to print anywhere that is visible outside of the enclave is a security issue.

For Linux, less so, as it a development platform and provides no real security.

**Comment by egrimley-arm** [comment]
I've made #567 to fix some of the issues here.
