### ISSUE TITLE
Veracruz-Client can't print results to stdout (Linux)

### ISSUE THREAD

**Issue by gbryant-arm** [veracruz-project/veracruz#566]
**Describe the bug**
On Linux, Veracruz-Client successfully receives results from the Runtime Manager but can't print them:
https://github.com/veracruz-project/veracruz/blob/27b9e4ace631904e1d76bffcf64f0193e12e0d7a/veracruz-client/src/cli.rs#L306
doesn't do anything.
Might be related to #565

**To Reproduce**
* Deploy Veracruz end-to-end on Linux
* Run a WASM program that writes something to either stdout, stderr or any other file
* Fetch the file: ```<client_path> --result <file>```

**Expected behaviour**
Veracruz-Client should print the content of the requested file.

**Comment by gbryant-arm** [comment]
That was a bug in my deployments scripts. Solved

**Comment by egrimley-arm** [comment]
Cool. I was just wondering why this wasn't detected by one of our CI tests.
