### ISSUE TITLE
TODO: Build CI container from GitHub Actions

### ISSUE THREAD

**Issue by mathias-arm** [veracruz-project/veracruz#574]
**Requested feature**

Add a GitHub Action workflow to build CI Docker Image.

**Motivation**

Make refreshing CI image easier and more repeatable by replacing the manual process. Include some best practices like image signing.

**Comment by dreemkiller** [comment]
What should trigger this action? Should it be manual only?

**Comment by mathias-arm** [comment]
Yes, only manual. I don't think we want to generate for each commit, and you have to be a member to trigger it.
