### ISSUE TITLE
Examples directory not updated in comments & doc

### ISSUE THREAD

**Issue by gbryant-arm** [veracruz-project/veracruz#608]
**Describe the bug**
Examples directory not updated in comments & doc:
- CLI_QUICKSTART.markdown
- data-generators/postcard-generator/src/main.rs
- execution-engine/README.markdown
- veracruz-mcu-client/run_mcu_test_server.sh
- workspaces/applications/Cargo.toml

**Expected behaviour**
Should point to `examples/rust-examples/` instead of `sdk/rust-examples`, which doesn't exist anymore

**Comment by mohamed-arm** [comment]
Fixed with https://github.com/veracruz-project/veracruz/pull/643 and https://github.com/veracruz-project/veracruz/pull/644.

**Comment by mohamed-arm** [comment]
Fixed with https://github.com/veracruz-project/veracruz/pull/643 and https://github.com/veracruz-project/veracruz/pull/644.
