### ISSUE TITLE
Command-line interface for user-facing components

### ISSUE THREAD

**Issue by geky** [veracruz-project/veracruz#63]
**Requested feature**
Would be nice to have command-line interfaces for the various user-facing components of Veracruz: Tabasco, Sinaloa, and Veracruz

**Motivation**
A command-line interface would probably be the most natural way to run Tabasco and Sinaloa servers in production, and it may be an easier interface for new users to experiment with.

**Additional context**
Something like this is needed for https://github.com/veracruz-project/veracruz/issues/41, or any other non-rust clients.

**Comment by geky** [comment]
I'm currently working on this based on sinaloa-test, since it's required for #41, any suggestions or ideas on what would be useful in a CLI would be useful.

**Comment by dreemkiller** [comment]
Tabasco does have a command line feature, but sinaloa doesn't (which I agree is a problem).
Also, not much thought has been put into tabasco's CLI, so there's a bit of design work there as well.

**Comment by geky** [comment]
Ah! I completely missed that. I started with adding tabasco-cli/sinaloa-cli crates in the root, but instead do we want the CLIs as additional main.rs files in their respective crates?
