### ISSUE TITLE
Remove the get_enclave_name and get_enclave_cert functions from the Sinaloa trait

### ISSUE THREAD

**Issue by dreemkiller** [veracruz-project/veracruz#64]
**Requested feature**
Currently, the `Sinaloa `trait has two functions who's sole purpose is for testing: `get_enclave_name `and `get_enclave_cert`.

These functions should (eventually) be removed, and each of the structs implementing the trait should be changed.

**Motivation**
It was valuable in the beginning to have tests that wouldn't get mired down in the attestation flows. These functions were added to allow test code to query the enclave for the certificate and name, without going through the attestation process. This short-circuits the attestation process, which is certainly something we don't want anyone doing in a real deployment.

The question now is, do we still think we need the `no_attestation` tests? Or can we convert them to `with_attestation`, which would allow us to remove these dangerous functions?

**Comment by geky** [comment]
An alternative to bypassing the attestation flow, could we have a dummy attestation server that just gives an A-OK for any query for testing?

**Comment by dominic-mulligan-arm** [comment]
I think most no-attestation tests at the moment are basically testing exactly the same thing as the tests *with* attestation, even running the same WASM binaries on the same sets of inputs.  I think the situation would be different if these tests were testing a different corner of Veracruz, but they're not: they're merely less comprehensive than their counterparts.  As a result, I'd favour removing any test that doesn't exercise the attestation flows.

**Comment by ShaleXIONG** [comment]
These two APIs have been removed.
