### ISSUE TITLE
Sonora enclave functions are not easily discoverable

### ISSUE THREAD

**Issue by dreemkiller** [veracruz-project/veracruz#67]
**Describe the bug**
The SGX enclave entry functions for Sonora are not easily discoverable

**To Reproduce**
Try grepping for `sinaloa_init_remote_attestation_enc` in the project directory. You will find calls to it but not an implementation

**Expected behaviour**
To aide newcomers to the project, functions should be easy for them to find the implementations of.

**Additional context**
As part of the build process for SGX enclaves, the SGX tool `sgx_edger8r` is executed. It has an option` --use-prefix`, which adds the name of the source `edl` file to all of the generated symbols. This means that functions such as `init_remote_attestation_enc` are translated to `sinaloa_remote_attestation_enc`.

We should stop using the `--use-prefix` option and instead name the functions in the `edl ` file and the source with the name they will be called with.

**Comment by dominic-mulligan-arm** [comment]
With the removal of support for Intel SGX this is now irrelevant.
