### ISSUE TITLE
Remove RUNTIME_MANAGER_HASH from nitro-root-enclave/src/main.rs

### ISSUE THREAD

**Issue by dreemkiller** [veracruz-project/veracruz#70]
**Requested feature**
Remove `MEXICO_CITY_HASH` from `nitro-root-enclave/src/main.rs`. I don't think it necessary any more.

**Motivation**
I think it was added as a hack, but I think it's no longer needed.

**Additional context**
Before attestation was fully functional, we had to add the hash of mexico city to the nitro root enclave manaully. I think it's handled correctly now and this should be removed.

**Comment by dominic-mulligan-arm** [comment]
I've just looked into this to understand the issue.  From tracing where `RUNTIME_MANAGER_HASH` is referenced (which is the relevant `Mutex` value, now, post Great Renaming), it is eventually bubbled up through `set_runtime_manager_hash` to a function that dispatches on incoming messages, with `set_runtime_manager_hash` being called in response to `NitroRootEnclaveMessage::SetRuntimeManagerHashHack(hash)` within that dispatcher function.  Is it the case that this message is now redundant, and can be removed?
